### ISSUE TITLE
This dialog looks non-native in Loki, and needs to be updated

### ISSUE THREAD

**Issue by dahenson** [elementary/pantheon-print#11] opened 2017-07-13 14:09 UTC
Coming from the contractor print contract that was executed in calendar, I discovered that this little gem (pantheon-print) looks bad in Loki, and it should feel bad. For a good, consistent interface across the board, this should be updated.
![calendarprintdialog](https://user-images.githubusercontent.com/2007067/28170408-f5ba1634-67aa-11e7-9dd6-898b9c841077.png)
![printdialogpagesetup](https://user-images.githubusercontent.com/2007067/28170512-3f5db8ae-67ab-11e7-8ab1-5adf4ab1dbe1.png)

**Comment by codygarver** [comment] 2018-05-18 19:15
The Print contract uses the native Gtk print dialog, which is pictured in your screenshot. The problem is it's a Gtk notebook, which elementary/stylesheet has Won't Fix'd this same bug for Epiphany's notebook. Closing since the Print contract has no control over this.

**Closed as completed by codygarver** 2018-05-18 19:15 UTC
